name: Build

on:
    push:
    pull_request:

jobs:
    build:
        name: Build project
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                conf_preset: [win64-visualstudio-clangcl, win64-visualstudio-msvc, ninja-multiconfig]
                build_type: [Debug]
                exclude:
                    - os: windows-latest
                      conf_preset: ninja-multiconfig
                    - os: ubuntu-latest
                      conf_preset: win64-visualstudio-clangcl
                    - os: ubuntu-latest
                      conf_preset: win64-visualstudio-msvc

        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout Project
              uses: actions/checkout@v4.2.2

            - name: Install CMake
              uses: ssrobins/install-cmake@v1
              with:
                version: 4.1.2
            
            - name: Build Project
              run: |
                cmake -S . -B build --preset ${{ matrix.conf_preset }}
                cmake --build --preset build-${{ matrix.conf_preset }}              